# Generated by Django 6.0.1 on 2026-04-02 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('cell_phone', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('At Practice', 'Practice'), ('Remote', 'Remote')], max_length=11)),
                ('pace', models.CharField(choices=[('8-9', 'Eight'), ('9-10', 'Nine'), ('10-11', 'Ten'), ('11-12', 'Eleven'), ('12-13', 'Twelve'), ('13+', 'Thirteen')], max_length=11)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('nyrr_race', models.CharField(max_length=150)),
                ('full_practice', models.BooleanField(default=True)),
                ('mentors', models.ManyToManyField(to='tfk_mentors.mentor')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfk_mentors.season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('practices', models.ManyToManyField(to='tfk_mentors.practice')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfk_mentors.season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestsSentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(default='sent', max_length=4)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfk_mentors.mentor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfk_mentors.requests')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MentorAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('practices', models.CharField(default='sent', max_length=4)),
                ('pace', models.CharField(choices=[('8-9', 'Eight'), ('9-10', 'Nine'), ('10-11', 'Ten'), ('11-12', 'Eleven'), ('12-13', 'Twelve'), ('13+', 'Thirteen')], max_length=5)),
                ('might_come_to_practice', models.BooleanField(default=False)),
                ('cant_make_practice', models.BooleanField(default=False)),
                ('comments', models.TextField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfk_mentors.mentor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfk_mentors.requests')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfk_mentors.season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mentor',
            name='seasons',
            field=models.ManyToManyField(to='tfk_mentors.season'),
        ),
    ]
