# Generated by Django 6.0.1 on 2026-05-07 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfk_mentors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('cell', models.CharField(max_length=20)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='tfk_mentors.season')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
