# Generated by Django 6.0.1 on 2026-05-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfk_mentors', '0002_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='nyrr_race',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
