# Generated by Django 6.0.1 on 2026-05-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfk_mentors', '0003_practice_nyrr_race_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='cell',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
