# Generated by Django 6.0.1 on 2026-05-07 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfk_mentors', '0004_coach_cell_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachPracticeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pace', models.CharField(choices=[('8-9', 'Eight'), ('9-10', 'Nine'), ('10-11', 'Ten'), ('11-12', 'Eleven'), ('12-13', 'Twelve'), ('13+', 'Thirteen')], max_length=11)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfk_mentors.coach')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfk_mentors.practice')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='practices',
            field=models.ManyToManyField(blank=True, related_name='coaches', through='tfk_mentors.CoachPracticeAssignment', to='tfk_mentors.practice'),
        ),
        migrations.AddConstraint(
            model_name='coachpracticeassignment',
            constraint=models.UniqueConstraint(fields=('coach', 'practice'), name='unique_coach_practice_assignment'),
        ),
    ]
