# Generated by Django 6.0.1 on 2026-05-07 02:45

from django.db import migrations, models


def copy_coach_season_to_m2m(apps, schema_editor):
    Coach = apps.get_model("tfk_mentors", "Coach")
    for coach in Coach.objects.exclude(season_id__isnull=True).iterator():
        coach.seasons.add(coach.season_id)


class Migration(migrations.Migration):

    dependencies = [
        ('tfk_mentors', '0005_coach_practice_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name="coach",
            name="seasons",
            field=models.ManyToManyField(
                blank=True, related_name="coaches", to="tfk_mentors.season"
            ),
        ),
        migrations.RunPython(copy_coach_season_to_m2m, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="coach",
            name="season",
        ),
    ]
