# Generated by Django 6.0.1 on 2026-05-07 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfk_mentors', '0006_coach_multi_seasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorPracticeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pace', models.CharField(choices=[('8-9', 'Eight'), ('9-10', 'Nine'), ('10-11', 'Ten'), ('11-12', 'Eleven'), ('12-13', 'Twelve'), ('13+', 'Thirteen')], max_length=11)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfk_mentors.mentor')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfk_mentors.practice')),
            ],
        ),
        migrations.AddField(
            model_name='mentor',
            name='practices',
            field=models.ManyToManyField(blank=True, related_name='mentor_assignments', through='tfk_mentors.MentorPracticeAssignment', to='tfk_mentors.practice'),
        ),
        migrations.AddConstraint(
            model_name='mentorpracticeassignment',
            constraint=models.UniqueConstraint(fields=('mentor', 'practice'), name='unique_mentor_practice_assignment'),
        ),
    ]
