# Generated by Django 6.0.1 on 2026-05-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfk_mentors', '0007_mentor_practice_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='split_practice',
            field=models.BooleanField(default=False),
        ),
    ]
