# Generated by Django 6.0.1 on 2026-06-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfk_mentors', '0013_mentor_practice_reply_mentor_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledemail',
            name='body_text',
            field=models.TextField(help_text='Message template. Use {{ first_name }}, {{ last_name }}, {{ year }}, {{ pace }}, and {{ link }} (personal reply URL); replaced per mentor when the email is sent.'),
        ),
        migrations.AlterField(
            model_name='scheduledemailmentorpracticereply',
            name='pace',
            field=models.CharField(blank=True, choices=[('8-9', 'Eight'), ('9-10', 'Nine'), ('10-11', 'Ten'), ('11-12', 'Eleven'), ('12-13', 'Twelve'), ('13+', 'Thirteen')], default='', max_length=11),
        ),
    ]
