# Generated by Django 6.0.1 on 2026-06-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfk_mentors', '0019_season_is_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='TfkStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('cell_phone', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name': 'TFK staff',
                'verbose_name_plural': 'TFK staff',
                'ordering': ['last_name', 'first_name', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='mentor',
            name='pace',
            field=models.CharField(blank=True, choices=[('8-9', 'Eight'), ('9-10', 'Nine'), ('10-11', 'Ten'), ('11-12', 'Eleven'), ('12-13', 'Twelve'), ('13+', 'Thirteen')], default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='scheduledemailmentorpracticereply',
            name='attendance',
            field=models.CharField(choices=[('attending', 'Attending'), ('not_attending', 'Not attending'), ('first_half', 'First half'), ('second_half', 'Second half'), ('available', 'Available')], max_length=20),
        ),
    ]
