# Generated by Django 6.0.1 on 2026-06-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfk_mentors', '0020_tfk_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
