# Generated by Django 6.0.1 on 2026-06-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfk_mentors', '0021_practice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachpracticeassignment',
            name='pace',
            field=models.CharField(blank=True, choices=[('8-9', 'Eight'), ('9-10', 'Nine'), ('10-11', 'Ten'), ('11-12', 'Eleven'), ('12-13', 'Twelve'), ('13+', 'Thirteen')], default='', max_length=11),
        ),
    ]
