# Generated by Django 6.0.1 on 2026-06-16 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfk_mentors', '0022_coach_practice_pace_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='start_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='season',
            name='head_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_coach_seasons', to='tfk_mentors.coach'),
        ),
    ]
