# Generated by Django 6.0.1 on 2026-06-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tfk_mentors", "0023_practice_start_location_season_head_coach"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeReminderEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scheduled_send_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Default: 6:15 AM the morning after anchor practice.",
                    ),
                ),
                (
                    "subject",
                    models.TextField(
                        help_text=(
                            "Subject template. Use {{ date_of_practice_1 }}, "
                            "{{ date_of_practice_2 }}, and {{ first_name }} / "
                            "{{ last_name }} for the recipient."
                        ),
                    ),
                ),
                (
                    "body_text",
                    models.TextField(
                        help_text=(
                            "Body template. Use {{ first_name }}, {{ last_name }}, "
                            "{{ year }}, {{ date_of_practice_1 }}, "
                            "{{ date_of_practice_2 }}, {{ practice_1_section }}, "
                            "{{ practice_2_section }}, {{ mentor_practice_1_notice }}, "
                            "{{ mentor_practice_2_notice }}."
                        ),
                    ),
                ),
                (
                    "task_completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the send task finished (null if not run yet).",
                        null=True,
                    ),
                ),
                (
                    "recipients_emailed_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How many recipients received this email when it was sent.",
                        null=True,
                    ),
                ),
                (
                    "anchor_practice",
                    models.OneToOneField(
                        help_text="Practice after which this reminder is scheduled to send.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_reminder_email",
                        to="tfk_mentors.practice",
                    ),
                ),
                (
                    "practice_one",
                    models.ForeignKey(
                        help_text="First upcoming practice covered in this email.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_reminders_as_first",
                        to="tfk_mentors.practice",
                    ),
                ),
                (
                    "practice_two",
                    models.ForeignKey(
                        blank=True,
                        help_text="Second upcoming practice covered in this email, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="practice_reminders_as_second",
                        to="tfk_mentors.practice",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_reminder_emails",
                        to="tfk_mentors.season",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_send_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PracticeReminderSendRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("recipient_first_name", models.CharField(blank=True, max_length=100)),
                ("recipient_last_name", models.CharField(blank=True, max_length=100)),
                (
                    "recipient_kind",
                    models.CharField(
                        choices=[
                            ("staff", "TFK Staff"),
                            ("coach", "Coach"),
                            ("mentor", "Mentor"),
                        ],
                        max_length=16,
                    ),
                ),
                ("rendered_subject", models.TextField()),
                ("rendered_body", models.TextField()),
                ("sent_at", models.DateTimeField()),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="send_records",
                        to="tfk_mentors.practicereminderemail",
                    ),
                ),
            ],
            options={
                "ordering": ["recipient_last_name", "recipient_first_name", "id"],
            },
        ),
    ]
