# Generated by Django 6.0.1 on 2026-06-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tfk_mentors", "0024_practice_reminder_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicereminderemail",
            name="kind",
            field=models.CharField(
                choices=[
                    ("before_first", "Before first practice"),
                    ("after_practice", "After practice"),
                ],
                default="after_practice",
                help_text="Whether this sends before the season's first practice or after an anchor practice.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="practicereminderemail",
            name="anchor_practice",
            field=models.ForeignKey(
                help_text=(
                    "For after-practice reminders, the practice after which this sends. "
                    "For before-first reminders, the season's first practice."
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practice_reminder_emails",
                to="tfk_mentors.practice",
            ),
        ),
        migrations.AlterField(
            model_name="practicereminderemail",
            name="scheduled_send_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text=(
                    "When to send automatically. After-practice default: 6:15 AM the morning after "
                    "anchor practice. Before-first default: 6:15 AM two days before the first practice. "
                    "Null means manual send only (e.g. first practice is less than 48 hours away)."
                ),
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="practicereminderemail",
            constraint=models.UniqueConstraint(
                fields=("anchor_practice", "kind"),
                name="unique_practice_reminder_anchor_kind",
            ),
        ),
    ]
