# Generated by Django 6.0.1 on 2026-06-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tfk_mentors", "0025_practice_reminder_before_first"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeReminderSuppression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("before_first", "Before first practice"),
                            ("after_practice", "After practice"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "anchor_practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_reminder_suppressions",
                        to="tfk_mentors.practice",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_reminder_suppressions",
                        to="tfk_mentors.season",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("anchor_practice", "kind"),
                        name="unique_practice_reminder_suppression",
                    )
                ],
            },
        ),
    ]
