# Generated by Django 6.0.1 on 2026-06-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfk_mentors', '0026_practice_reminder_suppression'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicereminderemail',
            options={'ordering': [models.OrderBy(models.F('scheduled_send_at'), nulls_last=True), 'id']},
        ),
    ]
