# Generated by Django 6.0.1 on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tfk_mentors", "0027_alter_practicereminderemail_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorpracticeassignment",
            name="is_available",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "When true, the mentor is listed as available for this practice "
                    "without an email reply row."
                ),
            ),
        ),
    ]
