# Generated by Django 6.0.1 on 2026-06-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tfk_mentors", "0028_mentor_practice_assignment_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="practice",
            name="attendance_comments",
            field=models.TextField(
                blank=True,
                default="",
                help_text="General notes recorded on the practice attendance page.",
            ),
        ),
        migrations.CreateModel(
            name="MentorPracticeShowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "show_up",
                    models.CharField(
                        choices=[("attended", "Attended"), ("missed", "Missed")],
                        max_length=10,
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tfk_mentors.mentor",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_show_ups",
                        to="tfk_mentors.practice",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="mentorpracticeshowup",
            constraint=models.UniqueConstraint(
                fields=("mentor", "practice"),
                name="unique_mentor_practice_show_up",
            ),
        ),
    ]
