# Generated by Django 6.0.1 on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tfk_mentors", "0029_practice_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="practice",
            name="show_to_mentors",
            field=models.BooleanField(
                default=False,
                help_text="When true, this practice appears on the public mentor directory.",
            ),
        ),
    ]
