# Generated by Django 6.0.1 on 2026-07-26 00:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfk_mentors', '0032_practice_mentor_selection_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledemail',
            name='recipient_mode',
            field=models.CharField(choices=[('all_in_season', 'All mentors in season'), ('all_at_practice_in_season', 'All At Practice mentors in season'), ('all_remote_in_season', 'All Remote mentors in season'), ('specific_mentors', 'Specific mentors')], default='all_in_season', help_text='Whether to email every mentor in a season or only selected mentors.', max_length=32),
        ),
        migrations.CreateModel(
            name='MentorCellPhoneRequestSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(db_index=True)),
                ('recipients_emailed_count', models.PositiveIntegerField(default=0)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_cell_phone_request_sends', to='tfk_mentors.season')),
            ],
            options={
                'ordering': ['-sent_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MentorCellPhoneRequestToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_phone_request_tokens', to='tfk_mentors.mentor')),
                ('send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='tfk_mentors.mentorcellphonerequestsend')),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('send', 'mentor'), name='unique_cell_phone_request_send_mentor')],
            },
        ),
    ]
