# Generated by Django 6.0.1 on 2026-07-31 19:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfk_mentors', '0033_mentor_cell_phone_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('outgoing_pace', models.CharField(blank=True, default='', max_length=11)),
                ('incoming_pace', models.CharField(blank=True, default='', max_length=11)),
                ('reject_comments', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('incoming_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_swap_requests', to='tfk_mentors.mentor')),
                ('outgoing_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_swap_requests', to='tfk_mentors.mentor')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='tfk_mentors.practice')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
