# Generated by Django 6.0.1 on 2026-08-03 23:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfk_mentors', '0034_mentor_swap_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderfilledPaceMentorEmailSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(db_index=True)),
                ('recipients_emailed_count', models.PositiveIntegerField(default=0)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='underfilled_pace_mentor_email_sends', to='tfk_mentors.season')),
            ],
            options={
                'ordering': ['-sent_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UnderfilledPaceMentorEmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_type', models.CharField(blank=True, choices=[('practices', 'Selected practices'), ('unavailable', 'Not available'), ('all_filled', 'All slots filled')], default='', max_length=20)),
                ('practice_ids', models.JSONField(blank=True, default=list, help_text='Practice ids offered in the email at send time.')),
                ('assigned_practice_ids', models.JSONField(blank=True, default=list, help_text="Practice ids assigned from this mentor's response.")),
                ('snagged_practice_ids', models.JSONField(blank=True, default=list, help_text='Practice ids selected but already full at submit time.')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='underfilled_pace_email_tokens', to='tfk_mentors.mentor')),
                ('send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='tfk_mentors.underfilledpacementoremailsend')),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('send', 'mentor'), name='unique_underfilled_pace_email_send_mentor')],
            },
        ),
    ]
